version: '2'

services:
  baikal:
    image: ckulka/baikal:apache
    restart: always
    environment:
      BAIKAL_SERVERNAME: dav.example.io
      BAIKAL_SERVERALIAS: dav.example.org dav.example.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - config:/var/www/baikal/Specific
      - data:/var/www/baikal/Specific
      # - /etc/ssl/private/baikal:/etc/ssl/private

volumes:
  config:
  data:
