version: "2"

services:
  baikal:
    image: ckulka/baikal:nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - baikal:/var/www/baikal/Specific

  backup:
    image: ckulka/awscli:alpine
    environment:
      - AWS_ACCESS_KEY_ID=my-access-key-id
      - AWS_SECRET_ACCESS_KEY=my-access-key-secret
      - AWS_DEFAULT_REGION=eu-central-1
      - BACKUP_LOCAL=/mnt
      - BACKUP_S3=s3://my-bucket
      # Specifying id of www-data, since the user doesn't exist in ckulka/awscli
      - BACKUP_CHOWN=33:33
    volumes:
      - baikal:/mnt
    command: sh /opt/aws-s3-sync-backup.sh

# To manually backup, run docker-compose run --rm backup
# To manually restore, run docker-compose run --rm backup sh /opt/aws-s3-sync-restore.sh

volumes:
  baikal:
